In [2]:
import numpy as np

In [3]:
zeros = np.zeros(10)
zeros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
ones = np.ones(10)
ones

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [5]:
array = np.full(10, 0.0)
array

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [6]:
a = np.array([1, 2, 3, 5, 7, 12])
a

array([ 1,  2,  3,  5,  7, 12])

In [7]:
a[2] = 10

In [8]:
a

array([ 1,  2, 10,  5,  7, 12])

In [9]:
np.arange(3, 10)

array([3, 4, 5, 6, 7, 8, 9])

In [10]:
np.linspace(0, 100, 11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [11]:
np.zeros((5, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [38]:
n = np.array([
    [2, 3, 7],
    [5, 6, 23],
])

In [40]:
m = np.array([
    [2, 3],
    [5, 6],
    [9, 7],
    [8, 2],
])

In [41]:
n

array([[ 2,  3,  7],
       [ 5,  6, 23]])

In [21]:
np.random.seed(2)
100 * np.random.randn(3,2)

array([[ -41.67578474,   -5.62668272],
       [-213.61960957,  164.02708084],
       [-179.34355852,  -84.17473657]])

In [44]:
p = m.dot(n)

In [26]:
a = np.arange(3, 10)
b = np.arange(2, 9)
a 

array([3, 4, 5, 6, 7, 8, 9])

In [27]:
b

array([2, 3, 4, 5, 6, 7, 8])

In [33]:
a.dot(b)

np.int64(238)

In [25]:
a>=3

array([ True,  True,  True,  True,  True,  True,  True])

In [47]:
ps = p[[0, 1, 2]]
ps

array([[ 19,  24,  83],
       [ 40,  51, 173],
       [ 53,  69, 224]])

In [57]:
r = np.array([
    [2, 3, 7],
    [5, 6, 23],
    [4, 2, 4],
])
r

array([[ 2,  3,  7],
       [ 5,  6, 23],
       [ 4,  2,  4]])

In [58]:
r_inv = np.linalg.inv(r)
r_inv

array([[-0.2972973 ,  0.02702703,  0.36486486],
       [ 0.97297297, -0.27027027, -0.14864865],
       [-0.18918919,  0.10810811, -0.04054054]])

In [60]:
r.dot(r_inv)

array([[ 1.00000000e+00,  1.38777878e-17, -5.55111512e-17],
       [ 4.16333634e-16,  1.00000000e+00,  1.66533454e-16],
       [ 3.33066907e-16,  0.00000000e+00,  1.00000000e+00]])

In [61]:
import pandas as pd